# Generated by Django 2.2.12 on 2021-04-09 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210408_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='orderedproducts',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='orderedproducts',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='orderedproducts',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Order'),
        ),
    ]
