# Generated by Django 2.2.12 on 2021-04-13 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210409_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='in_process',
        ),
        migrations.RemoveField(
            model_name='order',
            name='received',
        ),
    ]
